image: amdatu/build-jdk8-alpine
pipelines:
  default:
    - step:
        caches:
          - maven
          - gradle
        script:
          - bash ./gradlew buildPlugin --stacktrace
        after-script:
          - ls -lR /root/.gradle/caches/modules-2/files-2.1/com.jetbrains/jbre/
  branches:
    master:
      - step:
          caches:
            - maven
            - gradle
          script:
            - bash ./gradlew buildPlugin --stacktrace
            - curl -X POST "https://${BB_AUTH_STRING}@api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"build/distributions/amdatu-idea-2.2.1-SNAPSHOT.zip"
            - bash ./slack.sh ${SLACK_WEBHOOK}